#!/bin/bash

case $1 in
   config)

        cat << 'EOM'
graph_title Geiger Counter
graph_vlabel nSv_h
nSv_h.label nSv_h
EOM

exit 0;;
esac

#path to geigercouter.rb
head -2 /dev/ttyUSB0 | tail -1 | sed -re 's/.*CPM, (.+), uSv.*/nSv_h.value \1/g'